// Code generated by go-swagger; DO NOT EDIT.

package commits

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/sourcepods/sourcepods/pkg/api/v1/models"
)

// ListCommitsOKCode is the HTTP code returned for type ListCommitsOK
const ListCommitsOKCode int = 200

/*ListCommitsOK A list of all commits for that repository

swagger:response listCommitsOK
*/
type ListCommitsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Commit `json:"body,omitempty"`
}

// NewListCommitsOK creates ListCommitsOK with default headers values
func NewListCommitsOK() *ListCommitsOK {

	return &ListCommitsOK{}
}

// WithPayload adds the payload to the list commits o k response
func (o *ListCommitsOK) WithPayload(payload []*models.Commit) *ListCommitsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list commits o k response
func (o *ListCommitsOK) SetPayload(payload []*models.Commit) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListCommitsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Commit, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
